services:
  docs:
    image: notely_local_docs
    container_name: notely_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./notely:/app/notely:z
    ports:
      - '9000:9000'
    command: /start-docs
